<?php
namespace Database\Seeders;
use App\Models\{ActivityType,Badge,Challenge,Post,Reward,User};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\{DB,Hash};
class DatabaseSeeder extends Seeder {
 public function run(): void {
  foreach ([['กานต์ กรีน','kan@greenpoint.test','user',2450,'ปลูกวันนี้ เพื่ออากาศที่ดีของวันพรุ่งนี้ 🌱'],['มิ้นท์ รักษ์โลก','mint@greenpoint.test','user',2100,'ชอบปลูกต้นไม้และงานคราฟต์จากวัสดุเหลือใช้'],['บีม ใจเขียว','beam@greenpoint.test','user',1850,'ทุกก้าวเล็ก ๆ เปลี่ยนโลกได้'],['ผู้ดูแล GreenPoint','admin@greenpoint.test','admin',0,'ทีมงาน GreenPoint']] as $u) User::create(['name'=>$u[0],'email'=>$u[1],'role'=>$u[2],'points'=>$u[3],'bio'=>$u[4],'password'=>Hash::make('password')]);
  foreach ([['ปลูกต้นไม้','🌳',20,'#27865f'],['ดูแลต้นไม้','💧',5,'#3d8fb1'],['เก็บขยะ','🧹',10,'#e1973d'],['แยกขยะ','♻️',5,'#4b9b5e'],['รีไซเคิล','🔄',10,'#7b75c8'],['ลดพลาสติก','🛍️',10,'#d66b6b'],['ปลูกป่า','🌲',50,'#1d6349']] as $t) ActivityType::create(['name'=>$t[0],'icon'=>$t[1],'points'=>$t[2],'color'=>$t[3]]);
  foreach ([['user_id'=>1,'activity_type_id'=>1,'title'=>'ต้นมะม่วงสมาชิกใหม่','content'=>'วันนี้ปลูกต้นมะม่วงหน้าบ้าน 2 ต้น อีกไม่กี่ปีก็คงได้ร่มเงาดี ๆ แล้ว','location'=>'เชียงใหม่','activity_date'=>now()->subDay(),'tree_count'=>2,'request_points'=>true,'status'=>'approved','points_awarded'=>40],['user_id'=>2,'activity_type_id'=>5,'title'=>'กระถางจากขวดเก่า','content'=>'เปลี่ยนขวดพลาสติกที่ไม่ได้ใช้ ให้กลายเป็นกระถางเพาะต้นอ่อน น่ารักและลดขยะด้วยค่ะ','location'=>'กรุงเทพฯ','activity_date'=>now()->subDays(2),'request_points'=>true,'status'=>'approved','points_awarded'=>10],['user_id'=>3,'activity_type_id'=>3,'title'=>'เช้าวันเสาร์ที่สวนชุมชน','content'=>'รวมพลังกับเพื่อนบ้านเก็บขยะรอบสวน ได้ทั้งพื้นที่สะอาดและเพื่อนใหม่ครับ','location'=>'ขอนแก่น','activity_date'=>now()->subDays(3),'request_points'=>true,'status'=>'pending']] as $p) Post::create($p);
  DB::table('likes')->insert([['user_id'=>2,'post_id'=>1],['user_id'=>3,'post_id'=>1],['user_id'=>1,'post_id'=>2]]); DB::table('comments')->insert([['user_id'=>2,'post_id'=>1,'content'=>'เยี่ยมเลยค่ะ รอดูตอนโตนะคะ 🌿','created_at'=>now(),'updated_at'=>now()],['user_id'=>1,'post_id'=>2,'content'=>'ไอเดียดีมาก เดี๋ยวลองทำบ้างครับ','created_at'=>now(),'updated_at'=>now()]]);
  foreach ([['ต้นกล้ามะนาว','ต้นกล้าแข็งแรง พร้อมปลูก','🌱',120,18],['ชุดเมล็ดดอกไม้','ดอกไม้ไทย 5 สายพันธุ์','🌼',80,30],['ถุงผ้า GreenPoint','ผลิตจากผ้ารีไซเคิล','👜',250,12],['ขวดน้ำรักษ์โลก','สเตนเลสเก็บอุณหภูมิ','🧴',450,8],['Badge ผู้พิทักษ์ป่า','Badge รุ่นพิเศษบนโปรไฟล์','🏅',600,99]] as $r) Reward::create(['name'=>$r[0],'description'=>$r[1],'icon'=>$r[2],'points_required'=>$r[3],'stock'=>$r[4]]);
  foreach ([['First Plant','ปลูกต้นไม้ครั้งแรก','🌱','trees',1,20],['Green Starter','ปลูกต้นไม้ครบ 5 ต้น','🌿','trees',5,20],['Tree Lover','ปลูกต้นไม้ครบ 20 ต้น','🌳','trees',20,50],['Forest Guardian','ปลูกต้นไม้ครบ 50 ต้น','🌲','trees',50,100],['Green Hero','ทำกิจกรรมครบ 100 ครั้ง','🏆','activities',100,200]] as $b) Badge::create(['name'=>$b[0],'description'=>$b[1],'icon'=>$b[2],'criteria_type'=>$b[3],'criteria_value'=>$b[4],'bonus_points'=>$b[5]]);
  DB::table('user_badges')->insert([['user_id'=>1,'badge_id'=>1,'earned_at'=>now()],['user_id'=>1,'badge_id'=>2,'earned_at'=>now()],['user_id'=>2,'badge_id'=>1,'earned_at'=>now()]]);
  foreach ([['ปลูกให้โลกจำ','ปลูกต้นไม้ 3 ต้นภายในสัปดาห์','🌳',1,3,50],['รีไซเคิลฮีโร่','ทำกิจกรรมรีไซเคิล 3 ครั้ง','♻️',5,3,30],['รดน้ำต่อเนื่อง','ดูแลต้นไม้ให้ครบ 5 วัน','💧',2,5,40]] as $c) Challenge::create(['title'=>$c[0],'description'=>$c[1],'icon'=>$c[2],'activity_type_id'=>$c[3],'target'=>$c[4],'reward_points'=>$c[5],'starts_at'=>now()->startOfWeek(),'ends_at'=>now()->endOfWeek()]);
  DB::table('challenge_progress')->insert([['user_id'=>1,'challenge_id'=>1,'progress'=>2],['user_id'=>1,'challenge_id'=>2,'progress'=>1],['user_id'=>1,'challenge_id'=>3,'progress'=>4]]); DB::table('points_transactions')->insert([['user_id'=>1,'amount'=>40,'type'=>'earn','description'=>'ปลูกต้นมะม่วง 2 ต้น','balance_after'=>2450,'created_at'=>now(),'updated_at'=>now()],['user_id'=>1,'amount'=>50,'type'=>'earn','description'=>'สำเร็จภารกิจประจำสัปดาห์','balance_after'=>2410,'created_at'=>now()->subDays(2),'updated_at'=>now()->subDays(2)],['user_id'=>1,'amount'=>-120,'type'=>'spend','description'=>'แลกต้นกล้ามะนาว','balance_after'=>2360,'created_at'=>now()->subDays(5),'updated_at'=>now()->subDays(5)]]);
  foreach(['site_name'=>'GreenPoint','welcome_message'=>'ทุกกิจกรรมสีเขียวมีคุณค่า','maintenance_mode'=>'0','auto_approve_story'=>'1','ranking_enabled'=>'1','support_email'=>'support@greenpoint.local'] as $k=>$v) DB::table('system_settings')->insert(['key'=>$k,'value'=>$v,'type'=>in_array($k,['maintenance_mode','auto_approve_story','ranking_enabled'])?'boolean':'text','created_at'=>now(),'updated_at'=>now()]);
 }
}
