@extends('layouts.app')
@section('title','ศูนย์ผู้ดูแลระบบ')
@section('content')
<div class="page-head"><div><div class="eyebrow">ADMIN CONTROL CENTER</div><h1>ภาพรวมระบบ</h1><p>ตรวจสอบกิจกรรมและสุขภาพของชุมชน GreenPoint</p></div><span class="status approved">● ระบบทำงานปกติ</span></div>
<div class="stat-grid"><div class="stat"><i>👥</i><span>สมาชิกทั้งหมด<b>{{number_format($users)}}</b><small>บัญชี</small></span></div><div class="stat"><i>🌳</i><span>ต้นไม้ที่ปลูก<b>{{number_format($trees)}}</b><small>ต้น</small></span></div><div class="stat"><i>📝</i><span>โพสต์ทั้งหมด<b>{{number_format($posts)}}</b><small>โพสต์</small></span></div><div class="stat"><i>⭐</i><span>คะแนนที่แจก<b>{{number_format($points)}}</b><small>คะแนน</small></span></div></div>
<div class="admin-grid"><section class="card"><div class="card-head"><h2>กิจกรรมรอตรวจสอบ</h2><span class="count">{{$pending->count()}}</span></div>
@forelse($pending as $p)<div class="review"><div class="list-row"><div class="avatar">{{mb_substr($p->user->name,0,1)}}</div><span><b>{{$p->user->name}}</b><small>{{$p->created_at->diffForHumans()}}</small></span><em>{{$p->activityType?->icon}} {{$p->activityType?->name}}</em></div><h3>{{$p->title}}</h3><p>{{$p->content}}</p><div class="review-meta"><span>📍 {{$p->location??'ไม่ระบุ'}}</span><span>🌳 {{$p->tree_count}} ต้น</span><b>คาดการณ์ +{{($p->activityType?->points??0)*max(1,$p->tree_count)}} คะแนน</b></div><div class="review-actions"><form method="post" action="{{route('admin.review',$p)}}">@csrf<input type="hidden" name="status" value="rejected"><button class="btn danger">✕ ปฏิเสธ</button></form><form method="post" action="{{route('admin.review',$p)}}">@csrf<input type="hidden" name="status" value="approved"><button class="btn">✓ อนุมัติ</button></form></div></div>@empty<div class="empty">ไม่มีกิจกรรมรอตรวจสอบ 🎉</div>@endforelse</section>
<aside class="right"><div class="card"><h3>เมนูจัดการ</h3><div class="admin-links"><a href="{{route('admin.manage','users')}}">👥 จัดการสมาชิก <span>→</span></a><a href="{{route('admin.manage','activities')}}">🌱 ประเภทกิจกรรม <span>→</span></a><a href="{{route('admin.manage','rewards')}}">🎁 รางวัลและสต็อก <span>→</span></a><a href="{{route('admin.manage','redemptions')}}">📦 รายการแลกรางวัล <span>→</span></a><a href="{{route('admin.manage','challenges')}}">🎯 Challenge <span>→</span></a><a href="{{route('admin.manage','badges')}}">🏅 Badge <span>→</span></a><a href="{{route('admin.manage','reports')}}">🚩 รายงานเนื้อหา <span>→</span></a><a href="{{route('admin.manage','settings')}}">⚙ ตั้งค่าระบบ <span>→</span></a></div></div><div class="card"><h3>สต็อกรางวัล</h3>@foreach($rewards->take(4) as $r)<div class="stock"><span>{{$r->icon}} {{$r->name}}</span><b>{{$r->stock}}</b></div>@endforeach</div></aside></div>
@endsection
