@extends('layouts.app')
@section('title','จัดการระบบ — GreenPoint')
@section('content')
@php($titles=['users'=>['สมาชิก','ดูสถานะและระงับบัญชีผู้ใช้','👥'],'activities'=>['ประเภทกิจกรรม','กำหนดประเภทและคะแนนกิจกรรม','🌱'],'rewards'=>['รางวัลและสต็อก','เพิ่ม แก้ไข หรือนำรางวัลออกจากร้าน','🎁'],'redemptions'=>['รายการแลกรางวัล','ติดตามและอัปเดตขั้นตอนการรับรางวัล','📦'],'challenges'=>['Challenge','สร้างภารกิจและกำหนดคะแนนพิเศษ','🎯'],'badges'=>['Badge','กำหนดความสำเร็จและโบนัส','🏅'],'reports'=>['รายงานเนื้อหา','ตรวจสอบโพสต์ที่ถูกรายงาน','🚩'],'settings'=>['ตั้งค่าระบบ','ข้อมูลพื้นฐานและคุณสมบัติของแพลตฟอร์ม','⚙️']])
<div class="page-head"><div><a class="back-link" href="{{route('admin')}}">← ศูนย์ผู้ดูแล</a><h1>{{$titles[$section][2]}} {{$titles[$section][0]}}</h1><p>{{$titles[$section][1]}}</p></div>@if(in_array($section,['activities','rewards','challenges','badges']))<button class="btn" onclick="document.getElementById('create-panel').classList.toggle('show')">＋ เพิ่มรายการใหม่</button>@endif</div>
<div class="admin-tabs">@foreach($titles as $key=>$label)<a class="{{$section===$key?'active':''}}" href="{{route('admin.manage',$key)}}">{{$label[2]}} {{$label[0]}}</a>@endforeach</div>

@if($section==='users')
<div class="card table-card"><table><thead><tr><th>สมาชิก</th><th>บทบาท</th><th>คะแนน</th><th>โพสต์</th><th>สถานะ</th><th></th></tr></thead><tbody>@foreach($items as $u)<tr><td><div class="list-row"><div class="avatar tiny">{{mb_substr($u->name,0,1)}}</div><span><b>{{$u->name}}</b><small>{{$u->email}}</small></span></div></td><td>{{$u->role==='admin'?'ผู้ดูแล':'สมาชิก'}}</td><td>⭐ {{number_format($u->points)}}</td><td>{{$u->posts_count}}</td><td><em class="status {{$u->status==='active'?'approved':'rejected'}}">{{$u->status}}</em></td><td>@if($u->id!==auth()->id())<form method="post" action="{{route('admin.users.toggle',$u)}}">@csrf @method('PATCH')<button class="mini-btn {{$u->status==='active'?'danger-text':''}}">{{$u->status==='active'?'ระงับบัญชี':'เปิดใช้งาน'}}</button></form>@else<small>บัญชีปัจจุบัน</small>@endif</td></tr>@endforeach</tbody></table></div>

@elseif($section==='activities')
@include('partials.admin-create',['kind'=>'activity'])
<div class="manage-grid">@foreach($items as $item)<details class="card manage-card"><summary><i style="background:{{$item->color}}22">{{$item->icon}}</i><span><b>{{$item->name}}</b><small>{{$item->posts_count}} โพสต์</small></span><strong>+{{$item->points}} คะแนน</strong></summary><form class="admin-form" method="post" action="{{route('admin.activities.update',$item)}}">@csrf @method('PUT')<div class="form-grid"><label>ชื่อ<input name="name" value="{{$item->name}}" required></label><label>ไอคอน<input name="icon" value="{{$item->icon}}" required></label><label>คะแนน<input type="number" name="points" value="{{$item->points}}" min="0" required></label><label>สี<input type="color" name="color" value="{{$item->color}}" required></label></div><label class="check"><input type="checkbox" name="active" value="1" {{$item->active?'checked':''}}> เปิดใช้งาน</label><div class="form-actions"><button class="btn">บันทึก</button></form><form method="post" action="{{route('admin.activities.delete',$item)}}" onsubmit="return confirm('ยืนยันการลบประเภทกิจกรรม?')">@csrf @method('DELETE')<button class="btn danger">ลบ</button></form></div></form></details>@endforeach</div>

@elseif($section==='rewards')
@include('partials.admin-create',['kind'=>'reward'])
<div class="reward-grid">@foreach($items as $item)<details class="card reward manage-card"><summary><div class="reward-art">{{$item->icon}}</div><small>คงเหลือ {{$item->stock}}</small><h3>{{$item->name}}</h3><p>{{$item->description}}</p><b>⭐ {{number_format($item->points_required)}}</b></summary><form class="admin-form" method="post" action="{{route('admin.rewards.update',$item)}}">@csrf @method('PUT')<div class="form-grid"><label>ชื่อ<input name="name" value="{{$item->name}}" required></label><label>ไอคอน<input name="icon" value="{{$item->icon}}" required></label><label>คะแนนที่ใช้<input type="number" name="points_required" value="{{$item->points_required}}" required></label><label>สต็อก<input type="number" name="stock" value="{{$item->stock}}" min="0" required></label></div><label>รายละเอียด<textarea name="description" required>{{$item->description}}</textarea></label><label>สถานะ<select name="status"><option value="active" {{$item->status==='active'?'selected':''}}>แสดงในร้าน</option><option value="inactive" {{$item->status==='inactive'?'selected':''}}>ซ่อน</option></select></label><div class="form-actions"><button class="btn">บันทึก</button></form><form method="post" action="{{route('admin.rewards.delete',$item)}}" onsubmit="return confirm('ยืนยันการลบรางวัล?')">@csrf @method('DELETE')<button class="btn danger">ลบ</button></form></div></form></details>@endforeach</div>

@elseif($section==='redemptions')
<div class="card table-card"><table><thead><tr><th>ผู้แลก</th><th>รางวัล</th><th>รหัส</th><th>คะแนน</th><th>วันที่</th><th>สถานะ</th></tr></thead><tbody>@forelse($items as $item)<tr><td><b>{{$item->user->name}}</b><small>{{$item->user->email}}</small></td><td>{{$item->reward->icon}} {{$item->reward->name}}</td><td><code>{{$item->redemption_code}}</code></td><td>-{{number_format($item->points_spent)}}</td><td>{{$item->created_at->format('d/m/Y H:i')}}</td><td><form method="post" action="{{route('admin.redemptions.status',$item)}}">@csrf @method('PATCH')<select class="status-select" name="status" onchange="this.form.submit()">@foreach(['pending'=>'รอตรวจสอบ','approved'=>'อนุมัติแล้ว','shipped'=>'จัดส่งแล้ว','completed'=>'สำเร็จ','cancelled'=>'ยกเลิก'] as $v=>$label)<option value="{{$v}}" {{$item->status===$v?'selected':''}}>{{$label}}</option>@endforeach</select></form></td></tr>@empty<tr><td colspan="6" class="empty">ยังไม่มีรายการแลกรางวัล</td></tr>@endforelse</tbody></table></div>

@elseif($section==='challenges')
@include('partials.admin-create',['kind'=>'challenge'])
<div class="challenge-grid">@foreach($items as $item)<details class="card challenge manage-card"><summary><div class="challenge-icon">{{$item->icon}}</div><small>{{$item->activityType?->name??'ทุกกิจกรรม'}}</small><h2>{{$item->title}}</h2><p>{{$item->description}}</p><b>เป้าหมาย {{$item->target}} · ⭐ +{{$item->reward_points}}</b></summary><form class="admin-form" method="post" action="{{route('admin.challenges.update',$item)}}">@csrf @method('PUT')@include('partials.challenge-fields',['challenge'=>$item])<div class="form-actions"><button class="btn">บันทึก</button></form><form method="post" action="{{route('admin.challenges.delete',$item)}}" onsubmit="return confirm('ยืนยันการลบ Challenge?')">@csrf @method('DELETE')<button class="btn danger">ลบ</button></form></div></form></details>@endforeach</div>

@elseif($section==='badges')
@include('partials.admin-create',['kind'=>'badge'])
<div class="manage-grid">@foreach($items as $item)<details class="card manage-card"><summary><i>{{$item->icon}}</i><span><b>{{$item->name}}</b><small>{{$item->description}}</small></span><strong>โบนัส +{{$item->bonus_points}}</strong></summary><form class="admin-form" method="post" action="{{route('admin.badges.update',$item)}}">@csrf @method('PUT')@include('partials.badge-fields',['badge'=>$item])<div class="form-actions"><button class="btn">บันทึก</button></form><form method="post" action="{{route('admin.badges.delete',$item)}}" onsubmit="return confirm('ยืนยันการลบ Badge?')">@csrf @method('DELETE')<button class="btn danger">ลบ</button></form></div></form></details>@endforeach</div>

@elseif($section==='reports')
<div class="card table-card"><table><thead><tr><th>ผู้รายงาน</th><th>โพสต์</th><th>เหตุผล</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>@forelse($items as $item)<tr><td>{{$item->reporter->name}}</td><td><b>{{$item->post?->title??'โพสต์ถูกลบ'}}</b><small>{{$item->post?->user?->name}}</small></td><td>{{$item->reason}}</td><td><form method="post" action="{{route('admin.reports.status',$item)}}">@csrf @method('PATCH')<select class="status-select" name="status" onchange="this.form.submit()"><option value="pending" {{$item->status==='pending'?'selected':''}}>รอตรวจสอบ</option><option value="reviewed" {{$item->status==='reviewed'?'selected':''}}>ตรวจแล้ว</option><option value="dismissed" {{$item->status==='dismissed'?'selected':''}}>ยกเลิก</option></select></form></td><td>@if($item->post)<form method="post" action="{{route('admin.posts.delete',$item->post)}}" onsubmit="return confirm('ลบโพสต์นี้ถาวร?')">@csrf @method('DELETE')<button class="mini-btn danger-text">ลบโพสต์</button></form>@endif</td></tr>@empty<tr><td colspan="5" class="empty">ยังไม่มีรายงานเนื้อหา</td></tr>@endforelse</tbody></table></div>

@elseif($section==='settings')
@php($settings=$items->pluck('value','key'))<form class="card settings-form" method="post" action="{{route('admin.settings.save')}}">@csrf @method('PUT')<h2>ข้อมูลเว็บไซต์</h2><div class="form-grid"><label>ชื่อเว็บไซต์<input name="site_name" value="{{$settings['site_name']??'GreenPoint'}}" required></label><label>อีเมลช่วยเหลือ<input type="email" name="support_email" value="{{$settings['support_email']??''}}" required></label></div><label>ข้อความต้อนรับ<input name="welcome_message" value="{{$settings['welcome_message']??''}}" required></label><h2>คุณสมบัติระบบ</h2><label class="setting-toggle"><span><b>โหมดปรับปรุงระบบ</b><small>แสดงว่าส่วนสมาชิกปิดปรับปรุงชั่วคราว</small></span><input type="checkbox" name="maintenance_mode" value="1" {{($settings['maintenance_mode']??0)?'checked':''}}></label><label class="setting-toggle"><span><b>เผยแพร่โพสต์ทั่วไปอัตโนมัติ</b><small>โพสต์ที่ไม่รับคะแนนไม่ต้องรอตรวจสอบ</small></span><input type="checkbox" name="auto_approve_story" value="1" {{($settings['auto_approve_story']??1)?'checked':''}}></label><label class="setting-toggle"><span><b>เปิด Leaderboard</b><small>อนุญาตให้แสดงตารางคะแนนชุมชน</small></span><input type="checkbox" name="ranking_enabled" value="1" {{($settings['ranking_enabled']??1)?'checked':''}}></label><button class="btn">บันทึกการตั้งค่า</button></form>
@endif
@endsection
