@extends('layouts.app')
@section('title','GreenPoint — ทุกกิจกรรมสีเขียวมีคุณค่า')
@section('content')
<div class="landing">
<header><a class="brand" href="#top"><span>G</span>GreenPoint</a><nav><a href="#how">วิธีใช้งาน</a><a href="#benefits">สิ่งที่คุณจะได้รับ</a><a href="{{route('login')}}">เข้าสู่ระบบ</a><a class="btn" href="{{route('register')}}">เริ่มต้นใช้งาน</a></nav></header>
<section id="top" class="hero"><div><div class="eyebrow">🌱 COMMUNITY FOR A GREENER WORLD</div><h1>เปลี่ยนทุกกิจกรรมสีเขียว<br>ให้มีคุณค่า <em>และรางวัล</em></h1><p>ร่วมปลูกต้นไม้ ดูแลสิ่งแวดล้อม แชร์แรงบันดาลใจ และสะสม GreenPoint เพื่อแลกรางวัลที่ดีต่อคุณและโลก</p><div class="hero-actions"><a class="btn big" href="{{route('register')}}">เริ่มสร้างโลกสีเขียว →</a><a class="play" href="#how">ดูวิธีใช้งาน ↓</a></div><div class="trust"><b>12,840</b> สมาชิกสีเขียว <b>38,250</b> ต้นไม้ที่ปลูก <b>1.2M</b> คะแนนที่สร้างการเปลี่ยนแปลง</div></div><div class="hero-art"><div class="sun"></div><div class="hill one"></div><div class="hill two"></div><div class="tree">🌳</div><div class="float-card f1">🌱<b>+20 GreenPoint</b><small>ปลูกต้นไม้สำเร็จ!</small></div><div class="float-card f2">🏆<b>Level Up!</b><small>คุณคือ Tree Lover</small></div></div></section>
<section class="feature-strip"><div><b>🌳 ปลูกและดูแล</b><span>บันทึกทุกกิจกรรมเพื่อโลก</span></div><div><b>⭐ สะสมคะแนน</b><span>รับคะแนนหลังการตรวจสอบ</span></div><div><b>🎁 แลกรางวัล</b><span>เลือกรางวัลรักษ์โลก</span></div><div><b>🤝 สร้างชุมชน</b><span>แชร์เรื่องราวและแรงบันดาลใจ</span></div></section>

<section id="how" class="landing-section how-section"><div class="section-intro"><div class="eyebrow">HOW IT WORKS</div><h2>เริ่มสร้างการเปลี่ยนแปลงได้ใน 4 ขั้นตอน</h2><p>ไม่ว่าคุณจะปลูกต้นไม้ เก็บขยะ หรือเริ่มลดพลาสติก ทุกกิจกรรมมีคุณค่าและบันทึกไว้ได้ง่าย ๆ</p></div><div class="steps"><article><span class="step-no">01</span><i>📸</i><h3>ทำกิจกรรมสีเขียว</h3><p>เลือกกิจกรรมที่คุณทำได้ในชีวิตประจำวัน เช่น ปลูกต้นไม้ รีไซเคิล หรือเก็บขยะ</p></article><b>→</b><article><span class="step-no">02</span><i>🌿</i><h3>โพสต์ผลงาน</h3><p>เล่าเรื่องราว เพิ่มรายละเอียด และแนบหลักฐานเพื่อส่งผลงานให้ผู้ดูแลตรวจสอบ</p></article><b>→</b><article><span class="step-no">03</span><i>⭐</i><h3>รับ GreenPoint</h3><p>เมื่อกิจกรรมได้รับการอนุมัติ คะแนนจะเพิ่มเข้าบัญชีและบันทึกในประวัติโดยอัตโนมัติ</p></article><b>→</b><article><span class="step-no">04</span><i>🎁</i><h3>เติบโตและรับรางวัล</h3><p>ทำภารกิจ ปลดล็อก Badge เลื่อนระดับ และใช้คะแนนแลกรางวัลที่คุณชอบ</p></article></div><a class="btn big section-cta" href="{{route('register')}}">เริ่มกิจกรรมแรกของคุณ →</a></section>

<section id="benefits" class="landing-section benefits-section"><div class="benefit-copy"><div class="eyebrow">WHY GREENPOINT</div><h2>สิ่งดี ๆ ที่เติบโตไปพร้อมกับคุณ</h2><p>GreenPoint ไม่ได้ให้แค่คะแนน แต่ช่วยให้ทุกการลงมือของคุณมองเห็นได้ วัดผลได้ และส่งต่อแรงบันดาลใจให้คนรอบตัว</p><div class="benefit-list"><article><i>🌱</i><div><h3>เห็นผลลัพธ์ของตัวเอง</h3><p>ติดตามจำนวนต้นไม้ กิจกรรม คะแนน และผลกระทบเชิงบวกได้จากโปรไฟล์เดียว</p></div></article><article><i>🏅</i><div><h3>สนุกกับทุกความสำเร็จ</h3><p>สะสม Level, Badge และทำ Challenge เพื่อสร้างนิสัยรักษ์โลกอย่างต่อเนื่อง</p></div></article><article><i>🤝</i><div><h3>เป็นส่วนหนึ่งของชุมชน</h3><p>แบ่งปันเรื่องราว กดถูกใจ แสดงความคิดเห็น และเรียนรู้ไอเดียใหม่จากสมาชิก</p></div></article><article><i>🎁</i><div><h3>รับรางวัลที่มีความหมาย</h3><p>นำคะแนนไปแลกต้นกล้า เมล็ดพันธุ์ และของใช้ที่เป็นมิตรต่อสิ่งแวดล้อม</p></div></article></div></div><div class="benefit-visual"><div class="impact-card"><small>ผลลัพธ์ชุมชนเดือนนี้</small><div class="impact-big">🌍</div><b>8,420</b><span>กิจกรรมสีเขียว</span><div class="mini-stats"><div><b>3,780</b><span>ต้นไม้</span></div><div><b>12.4 ตัน</b><span>CO₂ ที่ช่วยลด</span></div></div></div><div class="benefit-badge bb1">🏆<b>100+ Challenges</b></div><div class="benefit-badge bb2">💚<b>ชุมชนที่เป็นมิตร</b></div></div></section>

<section class="landing-cta"><div><span>🌳</span><div><h2>พร้อมปลูกการเปลี่ยนแปลงแล้วหรือยัง?</h2><p>สมัครฟรี และเริ่มสะสม GreenPoint จากกิจกรรมแรกของคุณวันนี้</p></div></div><a class="btn big" href="{{route('register')}}">เข้าร่วม GreenPoint →</a></section>
<footer><a class="brand" href="#top"><span>G</span>GreenPoint</a><p>ทุกกิจกรรมสีเขียวมีคุณค่า © {{date('Y')}}</p><div><a href="#how">วิธีใช้งาน</a><a href="#benefits">สิ่งที่คุณจะได้รับ</a><a href="{{route('login')}}">เข้าสู่ระบบ</a></div></footer>
</div>
@endsection
