<?php

use App\Http\Controllers\GreenPointController as G; use Illuminate\Support\Facades\Route;
Route::get('/',[G::class,'home']); Route::get('/login',[G::class,'loginForm'])->name('login'); Route::post('/login',[G::class,'login']); Route::get('/register',[G::class,'registerForm'])->name('register'); Route::post('/register',[G::class,'register']);
Route::middleware('auth')->group(function(){
 Route::post('/logout',[G::class,'logout'])->name('logout'); Route::get('/feed',[G::class,'feed'])->name('feed'); Route::post('/posts',[G::class,'storePost'])->name('posts.store'); Route::post('/posts/{post}/like',[G::class,'like'])->name('posts.like'); Route::post('/posts/{post}/comments',[G::class,'comment'])->name('comments.store');
 Route::get('/dashboard',[G::class,'dashboard'])->name('dashboard'); Route::get('/profile/{user?}',[G::class,'profile'])->name('profile'); Route::get('/activities',[G::class,'activities'])->name('activities'); Route::get('/points',[G::class,'points'])->name('points'); Route::get('/rewards',[G::class,'rewards'])->name('rewards'); Route::post('/rewards/{reward}/redeem',[G::class,'redeem'])->name('rewards.redeem'); Route::get('/challenges',[G::class,'challenges'])->name('challenges'); Route::get('/leaderboard',[G::class,'leaderboard'])->name('leaderboard'); Route::get('/admin',[G::class,'admin'])->name('admin'); Route::post('/admin/posts/{post}/review',[G::class,'review'])->name('admin.review');
 Route::get('/admin/manage/{section}',[G::class,'adminManage'])->name('admin.manage'); Route::patch('/admin/users/{user}/toggle',[G::class,'toggleUser'])->name('admin.users.toggle');
 Route::post('/admin/activity-types',[G::class,'saveActivity'])->name('admin.activities.store'); Route::put('/admin/activity-types/{activityType}',[G::class,'saveActivity'])->name('admin.activities.update'); Route::delete('/admin/activity-types/{activityType}',[G::class,'deleteActivity'])->name('admin.activities.delete');
 Route::post('/admin/rewards',[G::class,'saveReward'])->name('admin.rewards.store'); Route::put('/admin/rewards/{reward}',[G::class,'saveReward'])->name('admin.rewards.update'); Route::delete('/admin/rewards/{reward}',[G::class,'deleteReward'])->name('admin.rewards.delete'); Route::patch('/admin/redemptions/{redemption}',[G::class,'redemptionStatus'])->name('admin.redemptions.status');
 Route::post('/admin/challenges',[G::class,'saveChallenge'])->name('admin.challenges.store'); Route::put('/admin/challenges/{challenge}',[G::class,'saveChallenge'])->name('admin.challenges.update'); Route::delete('/admin/challenges/{challenge}',[G::class,'deleteChallenge'])->name('admin.challenges.delete');
 Route::post('/admin/badges',[G::class,'saveBadge'])->name('admin.badges.store'); Route::put('/admin/badges/{badge}',[G::class,'saveBadge'])->name('admin.badges.update'); Route::delete('/admin/badges/{badge}',[G::class,'deleteBadge'])->name('admin.badges.delete');
 Route::patch('/admin/reports/{report}',[G::class,'reportStatus'])->name('admin.reports.status'); Route::delete('/admin/posts/{post}',[G::class,'deletePost'])->name('admin.posts.delete'); Route::put('/admin/settings',[G::class,'saveSettings'])->name('admin.settings.save');
});
