<?php
namespace App\Http\Controllers;
use App\Models\{ActivityType,Badge,Challenge,Comment,Like,PointsTransaction,Post,Report,Reward,RewardRedemption,SystemSetting,User}; use Illuminate\Http\Request; use Illuminate\Support\Facades\{Auth,DB,Hash}; use Illuminate\Support\Str;
class GreenPointController extends Controller {
 public function home(){return Auth::check()?redirect()->route('feed'):view('landing');} public function loginForm(){return view('auth',['mode'=>'login']);} public function registerForm(){return view('auth',['mode'=>'register']);}
 public function login(Request $r){$d=$r->validate(['email'=>'required|email','password'=>'required']);if(Auth::attempt($d)){if(Auth::user()->status!=='active'){Auth::logout();return back()->withErrors(['email'=>'บัญชีนี้ถูกระงับ กรุณาติดต่อผู้ดูแล']);}$r->session()->regenerate();return redirect()->route(Auth::user()->role==='admin'?'admin':'feed');}return back()->withErrors(['email'=>'อีเมลหรือรหัสผ่านไม่ถูกต้อง'])->onlyInput('email');}
 public function register(Request $r){$d=$r->validate(['name'=>'required|max:80','email'=>'required|email|unique:users','password'=>'required|min:8|confirmed']);$u=User::create(['name'=>$d['name'],'email'=>$d['email'],'password'=>Hash::make($d['password'])]);Auth::login($u);return redirect()->route('feed')->with('success','ยินดีต้อนรับสู่ GreenPoint!');} public function logout(Request $r){Auth::logout();$r->session()->invalidate();$r->session()->regenerateToken();return redirect('/');}
 public function feed(){return view('feed',['posts'=>Post::with(['user','activityType','likes','comments.user'])->where('privacy','public')->whereIn('status',['published','approved'])->latest()->get(),'types'=>ActivityType::where('active',1)->get()]);}
 public function storePost(Request $r){$d=$r->validate(['content'=>'required|max:2000','title'=>'nullable|max:120','activity_type_id'=>'nullable|exists:activity_types,id','tree_count'=>'nullable|integer|min:0','location'=>'nullable|max:120','activity_date'=>'nullable|date','privacy'=>'required|in:public,private']);$d+=['user_id'=>Auth::id(),'tree_count'=>$d['tree_count']??0,'request_points'=>$r->boolean('request_points')];$d['status']=$d['request_points']||SystemSetting::valueOf('auto_approve_story','1')!=='1'?'pending':'published';Post::create($d);return back()->with('success',$d['status']==='pending'?'ส่งโพสต์ให้ผู้ดูแลตรวจสอบแล้ว':'เผยแพร่โพสต์แล้ว');}
 public function like(Post $post){$q=Like::where(['user_id'=>Auth::id(),'post_id'=>$post->id])->first();$q?$q->delete():Like::create(['user_id'=>Auth::id(),'post_id'=>$post->id]);return back();} public function comment(Request $r,Post $post){$d=$r->validate(['content'=>'required|max:500']);Comment::create($d+['user_id'=>Auth::id(),'post_id'=>$post->id]);return back();}
 public function dashboard(){$u=Auth::user();return view('dashboard',['postCount'=>$u->posts()->count(),'treeCount'=>$u->posts()->where('status','approved')->sum('tree_count'),'pending'=>$u->posts()->where('status','pending')->count(),'recent'=>$u->posts()->latest()->take(4)->get()]);} public function profile(?User $user=null){$user=$user?:Auth::user();return view('profile',['profile'=>$user,'posts'=>$user->posts()->with(['activityType','likes','comments'])->latest()->get(),'badges'=>$user->badges]);} public function activities(){return view('activities',['posts'=>Auth::user()->posts()->with('activityType')->where('request_points',1)->latest()->get()]);} public function points(){return view('points',['transactions'=>PointsTransaction::where('user_id',Auth::id())->latest()->get()]);}
 public function rewards(){return view('rewards',['rewards'=>Reward::where('status','active')->get(),'redemptions'=>RewardRedemption::with('reward')->where('user_id',Auth::id())->latest()->get()]);} public function redeem(Reward $reward){$u=Auth::user();if($u->points<$reward->points_required||$reward->stock<1)return back()->withErrors(['reward'=>'คะแนนไม่พอหรือสินค้าหมด']);DB::transaction(function()use($u,$reward){$u->decrement('points',$reward->points_required);$reward->decrement('stock');RewardRedemption::create(['user_id'=>$u->id,'reward_id'=>$reward->id,'points_spent'=>$reward->points_required,'redemption_code'=>'GP-'.Str::upper(Str::random(8))]);PointsTransaction::create(['user_id'=>$u->id,'amount'=>-$reward->points_required,'type'=>'spend','description'=>'แลก '.$reward->name,'balance_after'=>$u->fresh()->points]);});return back()->with('success','แลกรางวัลสำเร็จแล้ว');}
 public function challenges(){return view('challenges',['challenges'=>Challenge::with('activityType')->where('active',1)->get(),'progress'=>DB::table('challenge_progress')->where('user_id',Auth::id())->get()->keyBy('challenge_id')]);} public function leaderboard(){abort_if(SystemSetting::valueOf('ranking_enabled','1')!=='1',404);return view('leaderboard',['users'=>User::where('role','user')->where('status','active')->where('join_ranking',1)->orderByDesc('points')->get()]);}
 public function admin(){abort_unless(Auth::user()->role==='admin',403);return view('admin',['users'=>User::count(),'posts'=>Post::count(),'trees'=>Post::where('status','approved')->sum('tree_count'),'points'=>PointsTransaction::where('amount','>',0)->sum('amount'),'pending'=>Post::with(['user','activityType'])->where('status','pending')->latest()->get(),'rewards'=>Reward::all()]);}
 public function review(Request $r,Post $post){abort_unless(Auth::user()->role==='admin',403);$status=$r->validate(['status'=>'required|in:approved,rejected'])['status'];DB::transaction(function()use($post,$status){$post->status=$status;if($status==='approved'){$type=$post->activityType;$earned=$type?($type->name==='ปลูกต้นไม้'?$type->points*max(1,$post->tree_count):$type->points):0;$post->points_awarded=$earned;$post->user->increment('points',$earned);PointsTransaction::create(['user_id'=>$post->user_id,'amount'=>$earned,'type'=>'earn','description'=>'อนุมัติกิจกรรม: '.($post->title?:$type?->name),'balance_after'=>$post->user->fresh()->points]);}$post->save();});return back()->with('success','อัปเดตผลการตรวจสอบแล้ว');}
 private function adminOnly():void { abort_unless(Auth::user()?->role==='admin',403); }
 public function adminManage(string $section){$this->adminOnly();abort_unless(in_array($section,['users','activities','rewards','redemptions','challenges','badges','reports','settings']),404);$data=['section'=>$section,'activityTypes'=>ActivityType::orderBy('name')->get()];if($section==='users')$data['items']=User::withCount('posts')->latest()->get();if($section==='activities')$data['items']=ActivityType::withCount('posts')->orderBy('name')->get();if($section==='rewards')$data['items']=Reward::latest()->get();if($section==='redemptions')$data['items']=RewardRedemption::with(['user','reward'])->latest()->get();if($section==='challenges')$data['items']=Challenge::with('activityType')->latest()->get();if($section==='badges')$data['items']=Badge::latest()->get();if($section==='reports')$data['items']=Report::with(['reporter','post.user'])->latest()->get();if($section==='settings')$data['items']=SystemSetting::orderBy('id')->get();return view('admin-manage',$data);}
 public function toggleUser(User $user){$this->adminOnly();abort_if($user->id===Auth::id(),422,'ไม่สามารถระงับบัญชีของตัวเอง');$user->update(['status'=>$user->status==='active'?'suspended':'active']);return back()->with('success','อัปเดตสถานะสมาชิกแล้ว');}
 public function saveActivity(Request $r,?ActivityType $activityType=null){$this->adminOnly();$d=$r->validate(['name'=>'required|max:80','icon'=>'required|max:10','points'=>'required|integer|min:0|max:10000','color'=>'required|max:20']);($activityType?:new ActivityType)->fill($d+['active'=>$r->boolean('active')])->save();return back()->with('success','บันทึกประเภทกิจกรรมแล้ว');}
 public function deleteActivity(ActivityType $activityType){$this->adminOnly();abort_if($activityType->posts()->exists(),422,'ลบไม่ได้ เนื่องจากมีกิจกรรมใช้งานประเภทนี้');$activityType->delete();return back()->with('success','ลบประเภทกิจกรรมแล้ว');}
 public function saveReward(Request $r,?Reward $reward=null){$this->adminOnly();$d=$r->validate(['name'=>'required|max:120','description'=>'required|max:500','icon'=>'required|max:10','points_required'=>'required|integer|min:1','stock'=>'required|integer|min:0','status'=>'required|in:active,inactive']);($reward?:new Reward)->fill($d)->save();return back()->with('success','บันทึกรางวัลแล้ว');}
 public function deleteReward(Reward $reward){$this->adminOnly();abort_if($reward->rewardRedemptions()->exists(),422,'ลบไม่ได้ เนื่องจากมีประวัติการแลกรางวัล');$reward->delete();return back()->with('success','ลบรางวัลแล้ว');}
 public function redemptionStatus(Request $r,RewardRedemption $redemption){$this->adminOnly();$redemption->update($r->validate(['status'=>'required|in:pending,approved,shipped,completed,cancelled']));return back()->with('success','อัปเดตสถานะการรับรางวัลแล้ว');}
 public function saveChallenge(Request $r,?Challenge $challenge=null){$this->adminOnly();$d=$r->validate(['title'=>'required|max:120','description'=>'required|max:500','icon'=>'required|max:10','activity_type_id'=>'nullable|exists:activity_types,id','target'=>'required|integer|min:1','reward_points'=>'required|integer|min:0','starts_at'=>'required|date','ends_at'=>'required|date|after_or_equal:starts_at']);($challenge?:new Challenge)->fill($d+['active'=>$r->boolean('active')])->save();return back()->with('success','บันทึก Challenge แล้ว');}
 public function deleteChallenge(Challenge $challenge){$this->adminOnly();DB::table('challenge_progress')->where('challenge_id',$challenge->id)->delete();$challenge->delete();return back()->with('success','ลบ Challenge แล้ว');}
 public function saveBadge(Request $r,?Badge $badge=null){$this->adminOnly();$d=$r->validate(['name'=>'required|max:100','description'=>'required|max:500','icon'=>'required|max:10','criteria_type'=>'required|in:trees,activities,points','criteria_value'=>'required|integer|min:1','bonus_points'=>'required|integer|min:0']);($badge?:new Badge)->fill($d)->save();return back()->with('success','บันทึก Badge แล้ว');}
 public function deleteBadge(Badge $badge){$this->adminOnly();DB::table('user_badges')->where('badge_id',$badge->id)->delete();$badge->delete();return back()->with('success','ลบ Badge แล้ว');}
 public function reportStatus(Request $r,Report $report){$this->adminOnly();$report->update($r->validate(['status'=>'required|in:pending,reviewed,dismissed']));return back()->with('success','อัปเดตรายงานแล้ว');}
 public function deletePost(Post $post){$this->adminOnly();$post->delete();return back()->with('success','ลบโพสต์และข้อมูลที่เกี่ยวข้องแล้ว');}
 public function saveSettings(Request $r){$this->adminOnly();$d=$r->validate(['site_name'=>'required|max:100','welcome_message'=>'required|max:255','support_email'=>'required|email']);foreach($d as $k=>$v)SystemSetting::updateOrCreate(['key'=>$k],['value'=>$v,'type'=>'text']);foreach(['maintenance_mode','auto_approve_story','ranking_enabled'] as $k)SystemSetting::updateOrCreate(['key'=>$k],['value'=>$r->boolean($k)?'1':'0','type'=>'boolean']);return back()->with('success','บันทึกการตั้งค่าระบบแล้ว');}
}
